<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Вебинары' => '',
    'Время добавления' => '',
    'Выберите класс' => '',
    'Выберите язык' => '',
    'Главная' => '',
    'Главная страница' => '',
    'Город' => '',
    'Данный ИИН уже зарегистрирован' => '',
    'Длина ИИН должен составлять 12 цифр' => '',
    'Для преподавателей' => '',
    'Для учеников' => '',
    'Жобалар' => '',
    'Журнал' => '',
    'Журналы' => '',
    'Заполните форму для участия в данной олимпиаде' => '',
    'ИИН' => '',
    'Имя' => '',
    'Класс' => '',
    'Конкурсы' => '',
    'Конференции' => '',
    'Материал жариялау' => '',
    'Материалы' => '',
    'Название' => '',
    'О нас' => '',
    'Ограничение вопросов' => '',
    'Ограничение по времени' => '',
    'Олимпиады' => '',
    'Оставшееся время:' => '',
    'Отправить' => '',
    'Перейти' => '',
    'Печатное дело' => '',
    'Предмет' => '',
    'Проекты' => '',
    'Регион' => '',
    'Регистрация' => '',
    'Редакция' => '',
    'Рисунок' => '',
    'Скачать' => '',
    'Тип' => '',
    'Турниры' => '',
    'Укажите школу' => '',
    'Учебный центр' => '',
    'Фамилия' => '',
    'Фотостудия' => '',
    'Школа' => '',
    'Язык' => '',
];
